### ISSUE TITLE
Certificate problem on the Github Page

### ISSUE THREAD

**Issue by Pab450** [johan-perso/discordwhois-library#1]
A Github page allows to avoid invalid certificate problems and to show directly an example that will be open source.

**Comment by Pab450** [comment]
My mistake, I had not seen that there was already a github page active but there is a problem of certificate ?

**Comment by johan-perso** [comment]
> My mistake, I had not seen that there was already a github page active but there is a problem of certificate ?

Yep, I did directly add the example on this repo as it would only be a single "index.html" file.

The issue with the certificate was due to GitHub not able to provide the certificate, it should now work
![image](https://user-images.githubusercontent.com/41506568/209442808-1a265646-4225-4a63-a7bc-e57a88a3b828.png)
